### ISSUE TITLE
include correpSearch Widget

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#3]
https://correspsearch.net/?id=api_csLink

**Comment by tklampfl** [comment]
The feature should enable listing of letters from the same timespan.

**Comment by tklampfl** [comment]
The widget is present now. Maybe more configuration of the parameters is needed:
 - critical.xsl line 163
 - links.xsl line 163
 - plain.xsl line 163
 - edition.xsl line 163
