### ISSUE TITLE
header höhe auf tagebuch anpassen

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#32]
Der Sprung von einem Brief aufs Tagebuch führt zu einem verschieben der Linie unterhalb des Menüs. Die rote Linie sollte auf der Höhe der grünen Linie sein

**Comment by tklampfl** [comment]
Should be fixed.

![image](https://user-images.githubusercontent.com/56353369/73739435-7ede4480-4746-11ea-84ef-e1e61b9af0f3.png)
![image](https://user-images.githubusercontent.com/56353369/73739471-90bfe780-4746-11ea-80bc-35b4f62daed5.png)
