### ISSUE TITLE
bilder

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#33]
Aufgabe:
Einbinden von Faksimiles, wo sie vorhanden sind.

Ergebnis:
Das Attribut pb/@facs soll – wo der wert gesetzt ist – als fontawesome-symbol 
`<i class="fas fa-scroll"></i> `
im Text erscheinen. wenn man draufklickt wird man entweder zu einer externen seite geleitet, wenn es eine URL ist, oder der viewer wird gestartet.

Hinweise:
Der Viewer ist bereits in der dev-Version des Tagebuchs eingebunden, evtl. dort nachschlagen
[https://dse.acdh-dev.oeaw.ac.at/exist/apps/schnitzler-tagebuch/pages/show.html?document=entry__1909-11-08.xml&searchkey=30299](url)

Beispiel für URL:
1895-07-17_01
1904-08-17_01

Beispiel für Bilder:
1900-08-04_01
1905-03-11_01

Ich gebe ein paar Beispielbilddateien in den Ordner data/images. Der endgültige Server für die Bilder ist noch nicht klar. Da sollte dann nur ein Pfad geändert werden müssen

**Comment by tklampfl** [comment]
Für externe Links wurde im Fließtext ein Symbol eingefügt. Das fontawesome-symbol fa-scroll kann ich nicht finden.
![image](https://user-images.githubusercontent.com/56353369/73860581-0b1e6380-483c-11ea-8c57-ee08681702a4.png)
Es wurde auch ein Faksimile Link eingefügt. 
![image](https://user-images.githubusercontent.com/56353369/73860629-1e313380-483c-11ea-9df4-716fc574b228.png)
 Dieser funktioniert mit den Bildern aus dem Tagebuch. Es scheint ein eigener Server (Loris - https://loris.acdh.oeaw.ac.at) notwendig zu sein, damit das openseadragon Plugin die Bilder und dazugehörige Daten beziehen kann. Das muß mit jemandem, der sich hier auskennt, besprochen werden.

**Comment by tklampfl** [comment]
Brief zum Testen:
![image](https://user-images.githubusercontent.com/56353369/73860757-533d8600-483c-11ea-9462-97078e6ed184.png)

**Comment by tklampfl** [comment]
Alle Bilder wurden ins jpg2000 Format umgewandelt und auf den Server https://iiif.acdh.oeaw.ac.at hochgeladen.
Zwei Fälle sind behandelt:

- Einerseits externe Links: Diese werden in einem neuen Tab geöffnet.

- Andererseits Faksimiles aus Cambridge ("MS-SCHNITZLER..."). Diese werden in einem modalen Dialog angezeigt.

Was noch fehlt ist die Behandlung sonstiger Bilder in den xml-Dateien. Martin hat gesagt, dass er das macht.
