### ISSUE TITLE
start-seite

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#34]
sollte in etwa gleich aussehen wie die vom schnitzler-tagebuch

**Comment by tklampfl** [comment]
Die Startseite ist nun überarbeitet. Sie sieht allerdings nicht so aus, wie das Schnitzler-Tagebuch, weil das Layout mit der Spalte in der Mitte beibehalten wurde. Bitte ansehen, ob das so ok ist.

**Comment by tklampfl** [comment]
Nach positiver Rückmeldung von Martin wird dieses Issue geschlossen.
