### ISSUE TITLE
blau -> schwarz

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#35]
Es gibt immer noch blaue Elemente, diese Farbe weg. Z.B.: bei Suchergebnissen die "Spaltenanzeige" und die Logos für PDF Excel etc. Auch bei Inhaltsverzeichnissen etc.

http://localhost:8080/exist/apps/schnitzler-briefe/pages/hits.html?searchkey=pmb41991

**Comment by tklampfl** [comment]
Wenn ich nichts übersehen habe, dürfte das Problem gelöst sein.
