### ISSUE TITLE
Briefnetz erkunden

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#38]
Umformulieren: Logo BRIEFNETZ
und in die gleiche Zeile wie die anderen Punkte
und link in gray

**Comment by martinantonmueller** [comment]
Ich habe ihnen geschrieben

**Comment by martinantonmueller** [comment]
Antwort:

>  Tatsächlich sollte das Symbol sich recht leicht ändern lassen mit einem kleinen Workaround. Fügen Sie hierzu einfach folgende CSS-Definition in das CSS Ihrer Seite ein, den Abstand zum Text können Sie dann über das margin-right anpassen:
> 
```
> #exploreCorrespSearch svg {
>     float: left !important;
>     margin-right: 0.4em;
> }
```

Aber es scheint nicht zu funktionieren

**Comment by tklampfl** [comment]
Habe das Logo für das Briefnetzwerk nun positioniert. Es handelt sich dabei um ein browserspezifisches Feature. Im Firefox und MS Edge funktioniert es korrekt: 
![image](https://user-images.githubusercontent.com/56353369/73838285-a222f580-4813-11ea-8b84-a3cd0cff878f.png)
