### ISSUE TITLE
Anzeige von Fussnoten im Text

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#40]
geht momentan nicht
http://localhost:8080/exist/apps/schnitzler-briefe/pages/show.html?document=1894-04-04_01.xml&stylesheet=plain

**Comment by martinantonmueller** [comment]
bezieht sich auf das Element footnote (nicht note). am schönsten wäre: so lange nur 3 footnotes vorkommmen, mit sternchen zu arbeiten. (***), sonst mit Ziffern

**Comment by tklampfl** [comment]
Sollte gelöst sein. Testseiten: 1894-04-04_01.xml und 1893-08-24_01.xml. Es wurden allerdings nur Ziffern als Fußnotenzeichen realisiert.
