### ISSUE TITLE
search should include correspDesc and author

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#41]
Currently searching for "Mamroth" does not give the letters written bei Mamroth as a result

**Comment by csae8092** [comment]
in case 'search' means the fulltext search than you'll need to adjust the fulltext-index-configuration https://github.com/acdh-oeaw/schnitzler-briefe/blob/master/collection.xconf#L10

**Comment by martinantonmueller** [comment]
include 
tei:titleStmt/tei:title[@level='a']
tei:titleStmt/tei:author

und correspDesc
