### ISSUE TITLE
CSS-Probleme

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#47]
Kalender im Menü ist schwarz, obwohl die restlichen Menüpunkte grau
und wenn man den Kalender auswählt, hat das Jahr ein graues Mausover, obwohl man nicht klicken kann, sollte weiß sein.
<img width="510" alt="Bildschirmfoto 2020-02-05 um 12 38 21" src="https://user-images.githubusercontent.com/11441262/73838654-75231280-4814-11ea-94b5-0278c5f553bd.png">

**Comment by tklampfl** [comment]
Im Menü ist "Kalender" nun grau:
![image](https://user-images.githubusercontent.com/56353369/73843063-2b3f2a00-481e-11ea-87d4-7bf6dbef9d48.png)
Das Jahr hat kein sichtbares mouseover mehr, also weiß.
