### ISSUE TITLE
Personenverzeichnis: Leere Einträge

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#48]
Das Personenverzeichnis beginnt mit leeren Vornamen bzw. Einträgen, die mit "??" beginnen. Im Schnitzler-Tagebuch wurde das gelöst, so dass der Index voll ausschaut. Dort anschauen, wie das gemacht wurde und übernehmen.

**Comment by tklampfl** [comment]
Es finden sich im Personenverzeichnis keine Einträge mit leerem Zunahmen und keine Einträge mit "??" mehr.
![image](https://user-images.githubusercontent.com/56353369/73933806-8edc5c80-48dd-11ea-9c93-bdaaca733011.png)

**Comment by martinantonmueller** [comment]
Sorry, das war ein Missverständnis. Sie müssen schon da bleiben, aber eben am Ende des Index.

**Comment by martinantonmueller** [comment]
Zur Erklärung: Das sind alles Personen, die vorkommen. Wir wissen nur momentan (?) ihren Namen (noch?) nicht

**Comment by tklampfl** [comment]
Müssen auch die leeren Zeilen angezeigt werden, oder nur jene mit "??"?

**Comment by martinantonmueller** [comment]
Alle. Nur eben am Ende statt am Anfang

**Comment by tklampfl** [comment]
Scheint zu funktionieren.
![image](https://user-images.githubusercontent.com/56353369/73944413-d1f4fa80-48f2-11ea-9bec-7bc42b5404dd.png)
![image](https://user-images.githubusercontent.com/56353369/73944465-ecc76f00-48f2-11ea-9b71-ab3e92c62be1.png)
