### ISSUE TITLE
Symbole

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#50]
Unterschiedliche Größe der Logos unterhalb der Überschrift auf eine Größe – die kleine – anpassen:

https://dse.acdh-dev.oeaw.ac.at/exist/apps/schnitzler-briefe/pages/toc.html?collection=editions#_

vs.

https://dse.acdh-dev.oeaw.ac.at/exist/apps/schnitzler-briefe/pages/calendar.html

**Comment by tklampfl** [comment]
Die Logos sind nun alle von der gleichen Größe.
![image](https://user-images.githubusercontent.com/56353369/73953544-dd4f2280-4900-11ea-98a4-8bf7c2c03b06.png)
![image](https://user-images.githubusercontent.com/56353369/73953610-f061f280-4900-11ea-8b10-f09f09c420a6.png)
![image](https://user-images.githubusercontent.com/56353369/73953664-05d71c80-4901-11ea-8368-823fe29f51ea.png)
