### ISSUE TITLE
Index – Anzeige von mehreren hinterlegten Index-@refs 

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#67]
**Derzeit**
Wenn verschachtelte ref-Elemente oder ref-Elemente mit mehreren Werten ausgewählt werden, geht nur ein Modal-Fenster mit "Links" auf, aber keine Werte werden angezeigt.

Varianten des Problems:

1. `<rs type="person" subtype="implied" ref="#pmb43168 #pmb43169">Familie</rs>` Vgl. Familie in der zweiten Zeile von:
[https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1895-10-04_03.xml&stylesheet=plain
](https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1895-10-04_03.xml&stylesheet=plain
)
2. Verschachtelt:  `<rs type="work" ref="#34255" subtype="implied">
                        <rs ref="#12303" type="person">Mozart</rs>band</rs>` Vgl. erste Zeile [https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1897-07-16_01.xml&stylesheet=plain](https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1897-07-16_01.xml&stylesheet=plain)

**Gewünscht**
Mehrere Modal-Dialoge sollen untereinander aufgehen und die verschiedenen Werte anzeigen.

**Lösung**
Die Lösung ist wohl im custom.js zu suchen. 

**Achtung** 
Ein Bug führt dazu, dass wenn ein Modal geschlossen wird und das selbe neuerlich angeklickt, es sich verdoppelt.

**Comment by martinantonmueller** [comment]
Ich habe nun nochmals sauber die XSLTs überprüft und neue Versionen gepusht. Es war da mit den Leerzeichen ein ziemliches Gewirks, das nun behoben ist. Nun sollten solche Elemente im js - Modal landen:

`<a class="reference-black" data-keys="work:pmb33552 work:pmb29935 person:pmb2173">Anatol</a>`

**Comment by martinantonmueller** [comment]
In der jetzigen Version geht es nicht, es geht nur ein "Links"-Feld auf, aber nichts passiert. In der Fassung von Vorgestern gingen mehrere Dialoge auf, für jeden Eintrag eins. Das hat gepasst, bis auf einen seltsamen Bug: Wenn man das Modal schloss und nochmals auf den Eintrag klickte, öffnete sich statt vorher zwei nunmehr drei Fenster, und das wurde jedesmal mehr.

**Comment by martinantonmueller** [comment]
Außerdem werden momentan die Werk-Links entweder nicht angezeigt oder es erscheint der Autor, die Autorin, nicht das Werk.

**Comment by tklampfl** [comment]
Testfall:
Brief 1895-10-04_03.xml, 2. Zeile "Familie" anklicken: Es müssen zwei Modaldialoge untereinander erscheinen:
![grafik](https://user-images.githubusercontent.com/56353369/107333667-12fb8e00-6ab6-11eb-8f67-aed4d4c60b67.png)
Es gibt einen Spezialfall: Wenn der Request für den zweiten Modaldialog schneller ist, als der für den ersten, erscheint nur ein Modaldialog. Dies sollte nun aber behoben sein. Trotzdem darauf achten: Cache des Browsers leeren, und noch einmal versuchen.
