### ISSUE TITLE
url without template

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#69]
currently:
https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1906-09-08_01.xml&stylesheet=plain
works, but not without the stylesheet-addition

https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1906-09-08_01.xml

**Comment by skurzinz** [comment]
The fallback xsl is defined to be `/resources/xslt/xmlToHtml.xsl` in https://github.com/acdh-oeaw/schnitzler-briefe/blob/master/modules/app.xql#L22. If you change this to plain.xsl it should work as expected.

**Comment by martinantonmueller** [comment]
great, thank you! I fixed it by changing the variable though:
declare variable $app:defaultXsl := doc($config:app-root||'/resources/xslt/plain.xsl');
