### ISSUE TITLE
Index – Personen/Werke/… im Element physDesc

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#71]
**Derzeitiges Verhalten**
Das Feld physDesc wird in einem Modal ausgegeben. Wenn sich darin Indexeinträge finden, klappt die Ausgabe von diesen nicht, da das Modal in Modal bedeutet

**Gewünschte Ausgabe**
Das eine Modal soll geschlossen werden und das andere mit dem Indexeintrag aufgehen.

**Lösungswege**

1. Das Modal schließen vor Anzeige des neuen Modals
2. Eventuell ist es einfacher – siehe enhancement-issue – auf das Wikipedia-Menü zu wechseln, das das erste Modal ersetzen würde.

**Testfall**
Beispiel: Sandor Wolf, hier:

[https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1894-04-02_02.xml&stylesheet=plain&searchkey=pmb4342](https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=1894-04-02_02.xml&stylesheet=plain&searchkey=pmb4342)

**Comment by tklampfl** [comment]
Wenn man auf "Überlieferung" klickt, werden die früher aufgerufenen Modaldialoge mit angezeigt. Der Fehler liegt in Zeile 55 von custom.js:
`$('.modal-dialog').append(subTreeToInsert);`
Diese Anweisung hängt an jedes div mit Klasse "modal-dialog" den Modaldialog an.
Korrektur:
`$('#myModal .modal-dialog').append(subTreeToInsert);`

Testfall:
Dokument 1895-10-04_03.xml - zweite Zeile auf "Familie" klicken - Modaldialog schließen - auf "Überlieferung" klicken.

**Comment by tklampfl** [comment]
Zum eigentlichen Problem:
Brief 1894-04-02_02 - auf "Überlieferung" klicken. Es erscheint ein Modaldialog:
![grafik](https://user-images.githubusercontent.com/56353369/107341090-daac7d80-6abe-11eb-9367-3e226809f909.png)
Klickt man in diesem Modaldialog auf "Sandor Wolf" erscheint ein zweiter Modaldialog über dem ersten:
![grafik](https://user-images.githubusercontent.com/56353369/107341292-121b2a00-6abf-11eb-950b-f2c9c6a009a8.png)
Beide Dialoge können dann wieder geschlossen werden.

Frage: Soll das geändert werden? Was ist der Fehler?

**Comment by martinantonmueller** [comment]
Diese übereinander liegenden Modal-Dialoge sind schwer auseinanderzuhalten. Besser wäre, den einen zu schließen und den neuen zu öffnen. Wenn es geht nach dem Schließen wieder den vorigen öffnen, aber das ist nicht wichtig.

**Comment by tklampfl** [comment]
Nun wird der erste Modaldialog geschlossen, bevor der zweite angezeigt wird.
![grafik](https://user-images.githubusercontent.com/56353369/107401831-8c6d9d80-6b03-11eb-8b3d-aad27533d78b.png)
![grafik](https://user-images.githubusercontent.com/56353369/107401908-a60ee500-6b03-11eb-89b5-3c27d4e03572.png)
