### ISSUE TITLE
Kalender – Mehrere Briefe an einem Tag geordnet

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#73]
Es geht darum, wenn mehrere Briefe vom selben Tag ediert sind, beispielsweise der 
3. April 1900 oder der 
31. Juli 1899

dann sind diese nach bestimmten Regeln geordnet (etwa, weil ein Brief auf den anderen antwortet.) 

Derzeit werden die Briefe im Kalender als Popup ungeordnet als Liste angezeigt. Das soll angepasst werden, indem zusätzlich der Zähler des jeweiligen Tages berücksichtigt wird. Dieser ist zweistellig und als "@n" beim jeweiligen Datum in correspAction[@type='sent'] vermerkt:

<date when="1910-10-20" n="02">20. 10. 1910</date>

**Comment by tklampfl** [comment]
Die relevanten Dateien sind: /resources/xslt/plain - dort eine Zeile zur Ausgabe von n als id von h2 eingefügt, sowie /resources/js/calendar.custom - darin Code für das Sortieren nach dem id Attribut hinzugefügt.

Beispiel 3. April 1900:

Vorher:
![grafik](https://user-images.githubusercontent.com/56353369/106779253-1bcc0a00-6647-11eb-92a5-44a555751d43.png)
Nachher:
![grafik](https://user-images.githubusercontent.com/56353369/106779349-30a89d80-6647-11eb-97b8-1074c8afe433.png)
