### ISSUE TITLE
Wikipedia-Style-Menu

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#87]
**Derzeit**
Ist unterhalb des Brieftextes das sekundäre Menü, das dadurch notwendigerweise ein wenig flattert. Da die Bildschirme unterschiedlich groß sind, wird es vielen Menschen nicht angezeigt.

**Gewünscht**
Ein seitliches Menü zum Ein- und Ausklappen, wie es Wikipedia derzeit zunehmend implementiert. (Siehe: [https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements#July_2020:_Collapsible_sidebar,_maximum_width,_and_new_header_now_available_to_all_users_on_euwiki,_fawiki,_frwiktionary,_euwiki,_and_ptwikiversity](url))

In Verwendung findet es sich hier:

[https://pt.wikiversity.org/wiki/Página_principal](url)

Für die Briefseite würde das bedeuten: 
Unterhalb des roten Strichs, in der linken Ecke sollen die drei Striche sein, die mit Draufklicken das seitliche Menü einblenden. Die Formatierung und Anordnung im Menü würde ich übernehmen. Die Vorwärts- und Rückwärts-Blätterer würden an der jetzigen Stelle wegfallen.

**Lösung**
Den Code von Wikipedia kopieren?

**Comment by martinantonmueller** [comment]
gemeint ist die neue "einklappbare Seitenleiste" : https://fahrrad-datenautobahn.de/wikipedia/wikipedia-haesslich/

**Comment by tklampfl** [comment]
Das gewünschte Verhalten ist in bootstrap schon eingebaut, man muß also keinen JavaScript-Code schreiben, sondern nur den Button und die ein-/ausblendbaren Elemente mit den korrekten Attributen versehen.
In der Leseansicht (Stylesheet plain) findet sich das einblendbare Menü.
So sieht es aus:
![grafik](https://user-images.githubusercontent.com/56353369/108095502-3c9d5200-7080-11eb-9f84-960d2069eb81.png)
![grafik](https://user-images.githubusercontent.com/56353369/108095583-5048b880-7080-11eb-94fb-409de7f7bb86.png)
Folgende Dinge wären noch zu prüfen bzw. zu machen:

- Die Positionierung des Menüs könnte auch mittig erfolgen.
- Die Änderung könnte auch in die anderen Ansichten (links, critical) übernommen werden.

Martin, wenn ich das machen soll, teile mir das bitte mit.

**Comment by martinantonmueller** [comment]
Lieber Thomas, 
das ist nicht ganz das Gewünschte. Ziel ist ein Sidebar zum ein und ausklappen. Hier fügt er oberhalb des Textes eine Zeile hinzu, die man sehen kann – oder nicht. Gemeint ist so etwas:

[https://codepen.io/rijdz/pen/zybbVK](https://codepen.io/rijdz/pen/zybbVK)

**Comment by martinantonmueller** [comment]
Ich habe die bisherigen Änderungen in eine Datei plain-neu.xsl kopiert und eine alte plain.xsl wiederhergestellt, damit ich ein Update machen konnte. Einfach dann wieder rückgängig machen

**Comment by tklampfl** [comment]
Nun sieht es folgendermaßen aus:

![grafik](https://user-images.githubusercontent.com/56353369/108691441-cd01e980-74fb-11eb-9840-7669e1aa7e92.png)

![grafik](https://user-images.githubusercontent.com/56353369/108691482-d7bc7e80-74fb-11eb-9b40-6ce58b0aa6fc.png)

Änderungen in resources/xslt/plain.xsl

**Comment by martinantonmueller** [comment]
Ich habe mich nun damit gespielt, bin aber nicht recht glücklich geworden, accessability-wise. Es verunklärt die Situation nur weiter ohne tatsächlichen gewinn. darum hier nochmals der code festgehalten und damit die alte lösung verfeinert:

` <div class="col-md-2">
                
                    
                    <div>
                        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#navbar-left" aria-expanded="false" aria-controls="navbar-left"> 
                        <span class="sr-only">Toggle navigation</span>
                        <a href="#">
                                <i class="fa fa-bars"/>
                        </a>
                        </button>
                    </div>
                    
                
                    <div class="side-menu-container collapse" id="navbar-left" style="margin-left:10pt;">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i title="Critical Edition" class="fas fa-glasses"/> ANSICHT
                                        (<xsl:value-of select="$current-view-deutsch"/>) </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{concat('show.html?document=',$document,'&amp;stylesheet=links')}">
                                        <i title="With Links" class="fas fa-palette"/> LINKS</a>
                                    <a class="dropdown-item" href="{concat('show.html?document=',$document,'&amp;stylesheet=critical')}">
                                        <i title="Critical Edition" class="fas fa-glasses"/>
                                        KRITISCH</a>
                                    <a class="dropdown-item" href="{$path2source}">
                                        <i class="far fa-file-code"/> TEI-XML</a>
                                </div>
                            </li>
                            <xsl:choose>
                                <xsl:when test="not(//tei:teiHeader[1]/tei:revisionDesc[1]/@status = 'approved')">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link" data-toggle="modal" data-target="#qualitaet">
                                            <span style="color: orange;">ENTWURF</span>
                                        </a>
                                    </li>
                                </xsl:when>
                                <xsl:otherwise/>
                            </xsl:choose>
                            <li class="nav-item dropdown">
                                <a class="nav-link" data-target="#ueberlieferung" role="button" data-toggle="modal" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-landmark"/> ÜBERLIEFERUNG </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" id="res-act-button-copy-url" data-copyuri="{$quotationString}">
                                    <span id="copy-url-button">
                                        <i class="fas fa-quote-right"/> ZITIEREN </span>
                                    <span id="copyLinkTextfield-wrapper">
                                        <span type="text" name="copyLinkInputBtn" id="copyLinkInputBtn" data-copyuri="{$quotationString}">
                                            <i class="far fa-copy"/>
                                        </span>
                                        <textarea rows="4" name="copyLinkTextfield" id="copyLinkTextfield" value="">
                                            <xsl:value-of select="$quotationString"/>
                                        </textarea>
                                    </span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <xsl:attribute name="target">
                                    <xsl:text>_blank</xsl:text>
                                </xsl:attribute>
                                <a class="nav-link">
                                    <xsl:attribute name="href">
                                        <xsl:value-of select="concat('https://schnitzler-tagebuch.acdh.oeaw.ac.at/pages/show.html?document=entry__', $datum, '.xml')"/>
                                    </xsl:attribute>
                                    <i class="fas fa-external-link-alt"/> TAGEBUCH
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <span class="nav-link">
                                    <div id="csLink" data-correspondent-1-name="" data-correspondent-1-id="all" data-correspondent-2-name="" data-correspondent-2-id="" data-start-date="{$datum}" data-end-date="" data-range="50" data-selection-when="before-after" data-selection-span="median-before-after" data-result-max="4" data-exclude-edition=""/>
                                </span>
                            </li>
                        </ul>
                    </div>
                
                </div>`
