### ISSUE TITLE
Kalender – Mehrere Einträge an einem Tag, Farbe

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#88]
Wenn mehr als zwei Einträge an einem Tag im Kalender sind, ist die Linie schwarz. Die sollte auch rot sein.

**Comment by tklampfl** [comment]
Änderung in bootstrap-year-calendar.min.js: <box-shadow: black> nach <box-shadow: rgb(166,52,55)> geändert.
Beispiel 12. August 1893 mit vier Briefen:
![image](https://user-images.githubusercontent.com/56353369/106432554-2d5ab980-646f-11eb-883c-8c9183442484.png)
