### ISSUE TITLE
Menü: Anzeige der Metadateien Indizes / Metatexte

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-briefe#91]
**Ausgangslage**
Der Menüpunkt Weiteres listet unter "Indizes" den Inhalt des Ordners /data/indices auf, unter Metatexte den des Ordners /data/meta
Wenn man dann auf eine Datei klickt, kommt eine Fehlermeldung.

**Fehler**
Das hat offensichtlich damit zu tun, dass die falsche URL gebaut wird. Diese lautet:

für Indices:
`show.html?document=listorg.xml&stylesheet=plain
`

bzw. für Meta-Texte:

`show.html?document=andere-drucke.xml&stylesheet=plain
`
sollte aber den richtigen Ordner enthalten:

`show.html?document=listorg.xml&stylesheet=plain&directory=indices
`
`show.html?document=andere-drucke.xml&stylesheet=plain&directory=meta
`

**Comment by tklampfl** [comment]
Die Fehlermeldung erscheint nicht mehr. Es werden die Indizes angezeigt.
![grafik](https://user-images.githubusercontent.com/56353369/107413944-aada9580-6b11-11eb-974d-2a235a6ad118.png)
Allerdings sind diese nur wenig formatiert.
